apiVersion: config.gatekeeper.sh/v1beta1
kind: K8sRunAsNonRoot
metadata:
  name: run-as-non-root
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["audit-zone"]
  parameters:
    message: "Containers must run as non-root with readOnlyRootFilesystem in audit-zone namespace"
