apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snoHostPath
spec:
  crd:
    spec:
      names:
        kind: K8sNoHostPath
      validation:
        type: object
        properties:
          message:
            type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snoHostPath
        
        violation[{"msg": msg}] {
            volume := input.review.object.spec.volumes[_]
            volume.hostPath
            msg := sprintf("HostPath volumes are not allowed: %v", [volume.name])
        }
